import antfu from '@antfu/eslint-config'

export default antfu(
  {
    typescript: true,
    vue: true,
    ignores: [
      '**/_archive/**',
      '**/.*/**',
      '**/*.json/**',
      '**/*.local/**',
      '**/*.log/**',
      '**/*.wasm.js/**',
      '**/*.mjs/**',
      '**/*.cjs/**',
      '**/bg.jpg/**',
      '**/build/**',
      '**/coverage/**',
      '**/data/**',
      '**/dist/**',
      '**/dist_*/**',
      '**/dist_macos/**',
      '**/dist_electron/**',
      '**/docker/**',
      '**/geoip/**',
      '**/help/**',
      '**/internal/**',
      '**/legacy/**',
      '**/logs/**',
      '**/node_modules/**',
      '**/npm-debug.log/**',
      '**/package-lock.json/**',
      '**/pnpm-lock.yaml/**',
      '**/public/**',
      '**/scripts/**',
      '**/tmp/**',
      '**/video/**',
      '**/wiki/**',
      '**/www/**',
      '**/yarn-error.log/**',
      '**/vite.config.ts/**',
      '**/vitest*/**',
      'zerva-vite/ssr-vue/*',
      'zerva-vite/ssr-vue/*/**',
      'examples/vite-ssr/*',
      'examples/vite-ssr/*/**'],
  },
  {},
  {
    rules: {
      'unused-imports/no-unused-vars': 'off',
      'antfu/consistent-list-newline': 'off',
      'eslint-disable-unused-imports/no-unused-imports': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-misused-promises': 'off',

      // Markdown in oui-float example throws error
      'vue/no-unused-refs': 'off',
    },
  },
)
